language: csharp
script:
  - xbuild /p:Configuration=Debug ./src/EasyImage/EasyImage.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ./src/EasyImage/EasyImage.sln
after_script:
  - nunit-console ./src/EasyImage/EasyImage.Tests/bin/Debug/EasyImage.Tests.dll
