language: csharp
solution: EasyImage.sln
mono: none
dotnet: 1.0.1
dist: trusty
branches:
  only:
    - master
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release tests/EasyImage.Tests.csproj
after_script:
  - dotnet pack -c Release src/EasyImage.csproj
  - dotnet nuget push src/bin/Release/*.nupkg -k $NUGET_API_KEY