language: csharp
solution: EasyImage.sln
mono: none
dotnet: 1.0.1
dist: trusty
branches:
  only:
    - master
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release tests/O7.EasyImage.Tests.csproj
after_script:
  - dotnet pack -c Release src/O7.EasyImage.csproj
  - dotnet nuget push src/bin/Release/O7.EasyImage.1.0.0.nupkg -k $NUGET_API_KEY -s https://nuget.org/