language: csharp
solution: ./src/easyImage/EasyImage.sln
script:
  - xbuild /p:Configuration=Debug ./src/easyImage/EasyImage.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ./src/easyImage/EasyImage.sln
