language: csharp
solution: EasyImage.sln
mono: none
dotnet: 1.0.1
dist: trusty
branches:
  only:
    - master
before_script:
  - dotnet restore
script:
  - dotnet build
  - dotnet test tests/EasyImage.Tests.csproj